# Generated by Django 3.2.15 on 2022-10-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aflink', '0002_alter_season_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='document',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
