# Generated by Django 3.2.15 on 2022-10-20 11:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aflink', '0004_auto_20221020_0858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buyer',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='buyer',
            new_name='customer',
        ),
    ]
