# Generated by Django 3.2.15 on 2022-10-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aflink', '0005_auto_20221020_1108'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='season',
            table='Item Receiving',
        ),
    ]
