# Generated by Django 3.2.15 on 2022-10-24 10:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aflink', '0006_alter_season_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Season',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='season',
            new_name='item',
        ),
    ]
