# Generated by Django 3.2.15 on 2022-10-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aflink', '0007_auto_20221024_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='item_name',
        ),
    ]
