# Generated by Django 3.2.15 on 2022-10-25 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aflink', '0008_rename_item_order_item_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='JobCard',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='jobcard',
        ),
    ]
