# Generated by Django 3.2.15 on 2022-10-27 12:11

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aflink', '0010_auto_20221027_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='material_requested',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.AutoField, to='aflink.material'),
        ),
    ]
