# Generated by Django 3.2.15 on 2022-10-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_buyer',
            new_name='is_customer',
        ),
    ]
